// apps/nuxt/app/pages/index.vue
<script setup lang="ts">
import { listings, formatUsd } from "@cf-bench/dataset";

useBenchPage("home");

const featured = listings.slice(0, 6);
</script>

<template>
  <div>
    <h1 class="h1">Cloudflare Framework Benchmark</h1>
    <div class="grid cols-3">
      <div class="card">
        <h2>MPA stays flow</h2>
        <p class="muted">Listing index and detail routes rendered by Nuxt on Workers.</p>
        <p><NuxtLink class="pill" to="/stays">Open stays</NuxtLink></p>
      </div>
      <div class="card">
        <h2>SPA chart flow</h2>
        <p class="muted">Interactive chart controls and canvas measurements.</p>
        <p><NuxtLink class="pill" to="/chart">Open chart</NuxtLink></p>
      </div>
      <div class="card">
        <h2>Media flow</h2>
        <p class="muted">Open and next interactions with benchmark markers.</p>
        <p><NuxtLink class="pill" to="/media">Open media</NuxtLink></p>
      </div>
    </div>

    <h2 style="margin-top: 24px">Featured stays</h2>
    <div class="grid cols-3">
      <NuxtLink v-for="listing in featured" :key="listing.id" class="card" :to="`/stays/${listing.id}`">
        <div style="font-weight: 700">{{ listing.title }}</div>
        <div class="small muted">{{ listing.city }}, {{ listing.country }}</div>
        <div style="margin-top: 8px">
          <strong>{{ formatUsd(listing.pricePerNight) }}</strong> <span class="muted small">/ night</span>
        </div>
      </NuxtLink>
    </div>
  </div>
</template>

// apps/waku/src/pages/index.tsx
export default async function HomePage() {
  return (
    <>
      <title>CF Bench</title>
      <section className="hero">
        <p className="eyebrow">Cloudflare Workers benchmark</p>
        <h1 className="h1">Cloudflare Framework Benchmark</h1>
        <p className="muted">
          Shared benchmark routes for stays, blog, chart, and media on Cloudflare Workers.
        </p>
      </section>
      <section className="grid cols-3 section">
        <a className="card feature-card" href="/stays">
          <strong>Stays flow</strong>
          <p className="muted">Multi-page listing index and detail routes with shared benchmark data.</p>
        </a>
        <a className="card feature-card" href="/chart">
          <strong>Chart flow</strong>
          <p className="muted">Interactive price chart with benchmark-ready controls and markers.</p>
        </a>
        <a className="card feature-card" href="/media">
          <strong>Media flow</strong>
          <p className="muted">Pre-rendered feed cards with client-side open and next interactions.</p>
        </a>
      </section>
    </>
  );
}
export const getConfig = async () => {
  return {
    render: 'static',
  } as const;
};
