// apps/tanstack-start-solid/src/components/HydrationMarker.tsx
import { onMount } from 'solid-js'

export function HydrationMarker() {
  onMount(() => {
    const w = window as Window & { __CF_BENCH__?: Record<string, any> }
    w.__CF_BENCH__ = w.__CF_BENCH__ || {}
    const hydration = (w.__CF_BENCH__.hydration = w.__CF_BENCH__.hydration || {})
    hydration.endMs = performance.now()
  })

  return null
}

// apps/tanstack-start/app/components/hydration-marker.tsx
import { useEffect } from "react";

function ensureHydrationStart() {
  if (typeof window === "undefined") return;
  const w = window as any;
  w.__CF_BENCH__ = w.__CF_BENCH__ || {};
  const hydration = (w.__CF_BENCH__.hydration = w.__CF_BENCH__.hydration || {});
  if (hydration.startMs == null) hydration.startMs = performance.now();
}

export function HydrationMarker() {
  ensureHydrationStart();
  useEffect(() => {
    if (typeof window === "undefined") return;
    const w = window as any;
    w.__CF_BENCH__ = w.__CF_BENCH__ || {};
    const hydration = (w.__CF_BENCH__.hydration = w.__CF_BENCH__.hydration || {});
    hydration.endMs = performance.now();
  }, []);

  return null;
}
