// apps/svelte/src/routes/stays/[id]/+page.svelte
<script lang="ts">
  import { formatUsd, type Listing } from "@cf-bench/dataset";
  export let data: { listing: Listing | undefined };
</script>

{#if data.listing}
  <h1 class="h1">{data.listing.title}</h1>

  <div class="card" style="padding:16px">
    <div class="muted small">
      {data.listing.city}, {data.listing.country} • {data.listing.bedrooms} bd • {data.listing.baths} ba • up to {data.listing.maxGuests} guests
    </div>

    <div style="margin-top:10px;display:flex;justify-content:space-between;gap:14px;flex-wrap:wrap">
      <div class="pill">★ {data.listing.rating} <span class="muted">({data.listing.reviews})</span></div>
      <div class="pill"><strong>{formatUsd(data.listing.pricePerNight)}</strong> <span class="muted">/ night</span></div>
      <a class="pill" href="/stays">← Back to results</a>
    </div>

    <div data-testid="stay-description" style="margin-top:14px">
      {@html data.listing.descriptionHtml}
    </div>
  </div>
{:else}
  <h1 class="h1">Stay not found</h1>
  <div class="card" style="padding:16px">
    <p>Unknown listing.</p>
    <a class="pill" href="/stays">Back</a>
  </div>
{/if}

// apps/next/app/stays/[id]/page.tsx
import { getListing, formatUsd } from "@cf-bench/dataset";

export default async function Page({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const l = getListing(id);

  if (!l) {
    return (
      <>
        <h1 className="h1">Stay not found</h1>
        <div className="card" style={{ padding: 16 }}>
          <p>Unknown listing.</p>
          <a className="pill" href="/stays">Back</a>
        </div>
      </>
    );
  }

  return (
    <>
      <h1 className="h1">{l.title}</h1>
      <div className="card" style={{ padding: 16 }}>
        <div className="muted small">
          {l.city}, {l.country} • {l.bedrooms} bd • {l.baths} ba • up to {l.maxGuests} guests
        </div>

        <div style={{ marginTop: 10, display: "flex", justifyContent: "space-between", gap: 14, flexWrap: "wrap" }}>
          <div className="pill">★ {l.rating} <span className="muted">({l.reviews})</span></div>
          <div className="pill"><strong>{formatUsd(l.pricePerNight)}</strong> <span className="muted">/ night</span></div>
          <a className="pill" href="/stays">← Back to results</a>
        </div>

        <div data-testid="stay-description" style={{ marginTop: 14 }} dangerouslySetInnerHTML={{ __html: l.descriptionHtml }} />
      </div>
    </>
  );
}
