// apps/svelte/src/routes/chart/+page.svelte
<script lang="ts">
  import { onMount, onDestroy, tick } from "svelte";
  import { createChartStore } from "@cf-bench/chart-hooks/svelte";
  import { markChartReady, markChartError, updateChartCoreMetrics } from "@cf-bench/bench-types";

  type ChartModule = typeof import("@cf-bench/chart-core");
  type ChartInstance = ReturnType<ChartModule["createChart"]>;

  const {
    symbol,
    timeframe,
    indicators,
    status,
    data,
    symbols,
    timeframes,
    setSymbol,
    setTimeframe,
    setIndicators,
    destroy,
  } = createChartStore();

  let canvas: HTMLCanvasElement;
  let chart: ChartInstance | null = null;
  let chartReady = false;
  let rafId: number | null = null;
  let error: string | null = null;
  let destroyed = false;

  onMount(async () => {
    try {
      await tick();
      if (!canvas) {
        throw new Error("Canvas element not found");
      }

      // Defer chart creation to next frame
      rafId = requestAnimationFrame(() => {
        void (async () => {
          try {
            const { createChart } = await import("@cf-bench/chart-core");
            if (destroyed) {
              return;
            }

            chart = createChart(canvas, {
              initialViewport: 180,
              onStats: (stats) => {
                updateChartCoreMetrics(stats);
              }
            });

            // Defer resize to next frame
            requestAnimationFrame(() => {
              try {
                if (destroyed) {
                  return;
                }

                chart?.resize();
                chart?.setIndicators($indicators);
                // Set initial data after chart is created
                if ($data) {
                  chart?.setCandles($data.candles);
                }
                chartReady = true;
                markChartReady($symbol, $timeframe);
              } catch (err) {
                error = err instanceof Error ? err.message : "Chart setup failed";
                markChartError(err instanceof Error ? err : "Chart setup failed");
              }
            });
          } catch (err) {
            error = err instanceof Error ? err.message : "Chart creation failed";
            markChartError(err instanceof Error ? err : "Chart creation failed");
          }
        })();
      });
    } catch (err) {
      error = err instanceof Error ? err.message : "Chart failed to load";
      markChartError(err instanceof Error ? err : "Chart failed to load");
    }
  });

  onDestroy(() => {
    destroyed = true;
    if (rafId !== null) {
      cancelAnimationFrame(rafId);
    }
    destroy();
    chart?.destroy?.();
  });

  // Update candles when data changes (with rAF)
  $: if ($data && chart && chartReady) {
    requestAnimationFrame(() => {
      chart?.setCandles($data.candles);
    });
  }

  // Update indicators when changed (with rAF)
  $: if (chart && chartReady) {
    requestAnimationFrame(() => {
      chart?.setIndicators($indicators);
    });
  }

  function handleSymbolChange(e: Event) {
    const target = e.target as HTMLSelectElement;
    setSymbol(target.value);
  }

  function handleTimeframeChange(e: Event) {
    const target = e.target as HTMLSelectElement;
    setTimeframe(target.value as any);
  }

  function handleIndicatorChange(key: "sma20" | "sma50" | "ema20" | "volume", e: Event) {
    const target = e.target as HTMLInputElement;
    setIndicators((prev) => ({ ...prev, [key]: target.checked }));
  }
</script>

<h1 class="h1">Chart (SPA-like)</h1>

{#if error}
  <div class="card" style="padding: 14px; border: 1px solid red; background: #fee;">
    <h2 style="color: red; margin: 0 0 8px 0;">Chart Error</h2>
    <p style="margin: 0;">{error}</p>
  </div>
{/if}

<div class="card" style="padding: 14px">
  <div style="display: flex; align-items: center; gap: 12px; flex-wrap: wrap">
    <div class="pill">
      <span class="muted small">Symbol</span>
      <select
        data-testid="symbol-select"
        class="input"
        style="width: 140px"
        value={$symbol}
        on:change={handleSymbolChange}
      >
        {#each symbols as s}
          <option value={s}>{s}</option>
        {/each}
      </select>
    </div>

    <div class="pill">
      <span class="muted small">Timeframe</span>
      <select
        data-testid="timeframe-select"
        class="input"
        style="width: 120px"
        value={$timeframe}
        on:change={handleTimeframeChange}
      >
        {#each timeframes as tf}
          <option value={tf}>{tf}</option>
        {/each}
      </select>
    </div>

    <div style="display: flex; align-items: center; gap: 10px">
      <label class="muted small" style="display: flex; gap: 6px; align-items: center">
        <input
          type="checkbox"
          checked={$indicators.sma20}
          on:change={(e) => handleIndicatorChange("sma20", e)}
        />
        SMA20
      </label>
      <label class="muted small" style="display: flex; gap: 6px; align-items: center">
        <input
          type="checkbox"
          checked={$indicators.sma50}
          on:change={(e) => handleIndicatorChange("sma50", e)}
        />
        SMA50
      </label>
      <label class="muted small" style="display: flex; gap: 6px; align-items: center">
        <input
          type="checkbox"
          checked={$indicators.ema20}
          on:change={(e) => handleIndicatorChange("ema20", e)}
        />
        EMA20
      </label>
      <label class="muted small" style="display: flex; gap: 6px; align-items: center">
        <input
          type="checkbox"
          checked={$indicators.volume}
          on:change={(e) => handleIndicatorChange("volume", e)}
        />
        Volume
      </label>
    </div>

    <div class="muted small">
      {$status === "loading" ? "Loading…" : $status === "error" ? "Error" : "Ready"}
    </div>
  </div>

  <div class="muted small" style="margin-top: 10px">
    Pan: drag • Zoom: mousewheel/trackpad • Crosshair: move cursor
  </div>

  <div style="height: 420px; margin-top: 12px; position: relative">
    {#if !chartReady}
      <div data-testid="chart-loading" style="position: absolute; inset: 0; display: flex; align-items: center; justify-content: center; background: var(--bg); border-radius: 12px; border: 1px solid var(--border);">
        <span class="muted">Loading chart…</span>
      </div>
    {:else}
      <div data-testid="chart-ready" style="position: absolute; inset: 0; pointer-events: none;"></div>
    {/if}
    <canvas
      bind:this={canvas}
      data-testid="chart-canvas"
      style="width: 100%; height: 100%; border-radius: 12px; border: 1px solid var(--border); opacity: {chartReady ? 1 : 0}; transition: opacity 0.2s ease-in-out;"
    ></canvas>
  </div>
</div>

// apps/solid/src/pages/Chart.tsx
import { createEffect, onCleanup, onMount, createSignal, For, Show, ErrorBoundary } from "solid-js";
import { useChart as useChartSolid } from "@cf-bench/chart-hooks/solid";
import { markChartError, updateChartCoreMetrics } from "@cf-bench/bench-types";
import { Layout } from "../components/Layout";

type ChartModule = typeof import("@cf-bench/chart-core");
type ChartInstance = ReturnType<ChartModule["createChart"]>;

export function Chart() {
  const [, setError] = createSignal<string | null>(null);

  return (
    <Layout title="Chart (SPA-like)">
      <ErrorBoundary
        fallback={(err) => (
          <div class="card" style="padding: 14px; border: 1px solid red; background: #fee;">
            <h2 style="color: red; margin: 0 0 8px 0;">Chart Error</h2>
            <p style="margin: 0;">{err.message || err.toString() || "Unknown error"}</p>
          </div>
        )}
      >
        <ChartInner onError={setError} />
      </ErrorBoundary>
    </Layout>
  );
}

function ChartInner(props: { onError: (error: string) => void }) {
  const {
    symbol,
    setSymbol,
    timeframe,
    setTimeframe,
    indicators,
    setIndicators,
    status,
    data,
    symbols,
    timeframes,
  } = useChartSolid();

  const [chartReady, setChartReady] = createSignal(false);
  let canvasRef: HTMLCanvasElement | undefined;
  let chart: ChartInstance | null = null;
  let initFrame: number | null = null;
  let updateFrame: number | null = null;
  let cancelled = false;

  const scheduleChartUpdate = (fn: () => void) => {
    if (updateFrame !== null) cancelAnimationFrame(updateFrame);
    updateFrame = requestAnimationFrame(() => {
      updateFrame = null;
      fn();
    });
  };

  onMount(() => {
    try {
      if (!canvasRef) {
        throw new Error("Canvas element not found");
      }

      initFrame = requestAnimationFrame(() => {
        void (async () => {
          try {
            const { createChart } = await import("@cf-bench/chart-core");
            if (cancelled || !canvasRef) return;

            chart = createChart(canvasRef, {
              initialViewport: 180,
              onStats: (stats) => updateChartCoreMetrics(stats),
            });
            chart.setIndicators(indicators());
            scheduleChartUpdate(() => {
              if (cancelled) return;
              chart?.resize();
              setChartReady(true);
            });
          } catch (err) {
            try {
              const errMsg = err instanceof Error ? err.message : "Chart setup failed";
              props.onError(errMsg);
              markChartError(errMsg);
            } catch (err) {
              props.onError("Chart setup failed");
              markChartError("Chart setup failed");
            }
          }
        })();
      });
    } catch (err) {
      const errMsg = err instanceof Error ? err.message : "Chart failed to load";
      props.onError(errMsg);
      markChartError(errMsg);
    }
  });

  onCleanup(() => {
    cancelled = true;
    if (initFrame !== null) cancelAnimationFrame(initFrame);
    if (updateFrame !== null) cancelAnimationFrame(updateFrame);
    chart?.destroy();
  });

  createEffect(() => {
    const candles = data();
    const nextIndicators = indicators();

    if (candles && chart) {
      scheduleChartUpdate(() => {
        chart?.setIndicators(nextIndicators);
        chart?.setCandles(candles.candles);
      });
    }
  });

  return (
    <>
      <h1 class="h1">Chart (SPA-like)</h1>
      <div class="card" style="padding: 14px">
        <div style="display: flex; align-items: center; gap: 12px; flex-wrap: wrap">
          <div class="pill">
            <span class="muted small">Symbol</span>
            <select
              data-testid="symbol-select"
              class="input"
              style="width: 140px"
              value={symbol()}
              onChange={(e) => setSymbol((e.target as HTMLSelectElement).value)}
            >
              <For each={symbols}>
                {(s) => (
                  <option value={s}>
                    {s}
                  </option>
                )}
              </For>
            </select>
          </div>

          <div class="pill">
            <span class="muted small">Timeframe</span>
            <select
              data-testid="timeframe-select"
              class="input"
              style="width: 120px"
              value={timeframe()}
              onChange={(e) => setTimeframe((e.target as HTMLSelectElement).value as any)}
            >
              <For each={timeframes}>
                {(tf) => (
                  <option value={tf}>
                    {tf}
                  </option>
                )}
              </For>
            </select>
          </div>

          <div style="display: flex; align-items: center; gap: 10px">
            <label class="muted small" style="display: flex; gap: 6px; align-items: center">
              <input
                type="checkbox"
                checked={indicators().sma20}
                onChange={(e) => setIndicators((prev) => ({ ...prev, sma20: (e.target as HTMLInputElement).checked }))}
              />
              SMA20
            </label>
            <label class="muted small" style="display: flex; gap: 6px; align-items: center">
              <input
                type="checkbox"
                checked={indicators().sma50}
                onChange={(e) => setIndicators((prev) => ({ ...prev, sma50: (e.target as HTMLInputElement).checked }))}
              />
              SMA50
            </label>
            <label class="muted small" style="display: flex; gap: 6px; align-items: center">
              <input
                type="checkbox"
                checked={indicators().ema20}
                onChange={(e) => setIndicators((prev) => ({ ...prev, ema20: (e.target as HTMLInputElement).checked }))}
              />
              EMA20
            </label>
            <label class="muted small" style="display: flex; gap: 6px; align-items: center">
              <input
                type="checkbox"
                checked={indicators().volume}
                onChange={(e) => setIndicators((prev) => ({ ...prev, volume: (e.target as HTMLInputElement).checked }))}
              />
              Volume
            </label>
          </div>

          <div class="muted small">
            {status() === "loading" ? "Loading…" : status() === "error" ? "Error" : "Ready"}
          </div>
        </div>

        <div class="muted small" style="margin-top: 10px">
          Pan: drag • Zoom: mousewheel/trackpad • Crosshair: move cursor
        </div>

        <div style="height: 420px; margin-top: 12px; position: relative">
          <Show when={!chartReady()}>
            <div data-testid="chart-loading" style="position: absolute; inset: 0; display: flex; align-items: center; justify-content: center; background: var(--bg); border-radius: 12px; border: 1px solid var(--border);">
              <span class="muted">Loading chart…</span>
            </div>
          </Show>
          <Show when={chartReady()}>
            <div data-testid="chart-ready" style="position: absolute; inset: 0; pointer-events: none;"></div>
          </Show>
          <Show when={status() === "error"}>
            <div data-testid="chart-error" style="position: absolute; inset: 0; display: flex; align-items: center; justify-content: center; background: var(--bg); border-radius: 12px; border: 1px solid var(--border);">
              <span class="muted">Chart error</span>
            </div>
          </Show>
          <canvas
            ref={canvasRef}
            data-testid="chart-canvas"
            style="width: 100%; height: 100%; border-radius: 12px; border: 1px solid var(--border); opacity: {chartReady() ? 1 : 0}; transition: opacity 0.2s ease-in-out;"
          />
        </div>
      </div>
    </>
  );
}
