// apps/react-router/app/routes/home.tsx
import { Link } from "react-router";

export default function HomeRoute() {
  return (
    <>
      <h1 className="h1">Framework benchmark harness</h1>
      <div className="grid cols-3">
        <div className="card">
          <h2>SPA-like</h2>
          <p className="muted">Interactive chart with symbol switching.</p>
          <p>
            <Link className="btn" to="/chart">
              Open chart
            </Link>
          </p>
        </div>
        <div className="card">
          <h2>App pages</h2>
          <p className="muted">Listings index + detail pages.</p>
          <p>
            <Link className="btn" prefetch="intent" to="/stays">
              Browse stays
            </Link>
          </p>
        </div>
        <div className="card">
          <h2>SSG blog</h2>
          <p className="muted">Prerendered route content.</p>
          <p>
            <Link className="btn" prefetch="intent" to="/blog">
              Read blog
            </Link>
          </p>
        </div>
        <div className="card">
          <h2>Media feed</h2>
          <p className="muted">Feed browsing and player interactions.</p>
          <p>
            <Link className="btn" to="/media">
              Open media
            </Link>
          </p>
        </div>
      </div>
    </>
  );
}

// apps/solid/src/pages/Home.tsx
import { createSignal, onMount, Show } from "solid-js";
import { Layout } from "../components/Layout";

export function Home() {
  const [mounted, setMounted] = createSignal(false);

  // Optimize: Show skeleton before mounting
  onMount(() => {
    // Defer rendering to next frame for smoother appearance
    requestAnimationFrame(() => {
      setMounted(true);
    });
  });

  return (
    <Layout title="Framework benchmark harness">
      <Show when={mounted()} fallback={
        <div class="card" style="padding: 16px; min-height: 400px;">
          <div class="skeleton" style="height: 28px; width: 200px; margin-bottom: 16px;" />
          <div class="grid cols-3">
            {[1, 2, 3].map((i) => (
              <div key={i} style="margin-bottom: 16px;">
                <div class="skeleton" style="height: 32px; width: 150px; margin-bottom: 8px;" />
                <div class="skeleton" style="height: 16px; width: 100%; margin-bottom: 12px;" />
                <div class="skeleton" style="height: 40px; width: 120px;" />
              </div>
            ))}
          </div>
        </div>
      }>
        <div class="grid cols-3">
          <div class="card" style="padding:16px">
            <h2>SPA-like</h2>
            <p class="muted">Interactive chart with symbol switching (no full reload).</p>
            <a class="btn" href="/chart">Open chart</a>
          </div>
          <div class="card" style="padding:16px">
            <h2>App pages</h2>
            <p class="muted">Listings index + detail pages (Airbnb-ish).</p>
            <a class="btn" href="/stays">Browse stays</a>
          </div>
          <div class="card" style="padding:16px">
            <h2>SSG blog</h2>
            <p class="muted">Prebuilt blog pages.</p>
            <a class="btn" href="/blog">Read blog</a>
          </div>
          <div class="card" style="padding:16px">
            <h2>Media feed</h2>
            <p class="muted">YouTube-like browse and player interactions.</p>
            <a class="btn" href="/media">Open media</a>
          </div>
        </div>

        <div class="card" style="padding:16px;margin-top:14px">
          <p class="muted small">
            This page is rendered client-side in Solid. Run the Playwright bench runner against each deployed framework.
          </p>
        </div>
      </Show>
    </Layout>
  );
}
