// apps/waku/src/pages/stays/index.tsx
import { formatUsd, queryListings } from '@cf-bench/dataset';

export default async function StaysPage() {
  const listings = queryListings({ page: 1, pageSize: 12 }).results;

  return (
    <>
      <title>CF Bench Stays</title>
      <section className="hero">
        <p className="eyebrow">Listings</p>
        <h1 className="h1">Stays</h1>
        <p className="muted">Airbnb-style listing cards served on Cloudflare Workers.</p>
      </section>
      <section className="grid cols-2 section">
        {listings.map((listing) => (
          <a key={listing.id} className="card listing-card" data-testid="stay-card" href={`/stays/${listing.id}`}>
            <strong>{listing.title}</strong>
            <p className="muted small">
              {listing.city}, {listing.country} • {listing.bedrooms} bd • {listing.baths} ba
            </p>
            <p>
              {formatUsd(listing.pricePerNight)} <span className="muted small">/ night</span>
            </p>
            <p className="muted">{listing.summary}</p>
          </a>
        ))}
      </section>
    </>
  );
}

export const getConfig = async () => ({ render: 'static' } as const);

// apps/nuxt/app/pages/stays/index.vue
<script setup lang="ts">
import { formatUsd, queryListings } from "@cf-bench/dataset";

useBenchPage("list");

const route = useRoute();
const page = Number(route.query.page || "1") || 1;
const data = queryListings({ page, pageSize: 12 });
</script>

<template>
  <div>
    <h1 class="h1">Stays</h1>
    <p class="muted">Airbnb-style listing index served on Cloudflare Workers.</p>

    <div class="grid cols-3" style="margin-top: 12px">
      <NuxtLink
        v-for="listing in data.results"
        :key="listing.id"
        :to="`/stays/${listing.id}`"
        data-testid="stay-card"
        class="card"
        no-prefetch
      >
        <div style="font-weight: 700">{{ listing.title }}</div>
        <div class="small muted">
          {{ listing.city }}, {{ listing.country }} • {{ listing.bedrooms }} bd • {{ listing.baths }} ba
        </div>
        <div style="margin-top: 8px">
          <strong>{{ formatUsd(listing.pricePerNight) }}</strong> <span class="muted small">/ night</span>
        </div>
      </NuxtLink>
    </div>
  </div>
</template>
