// apps/waku/src/pages/stays/[id].tsx
import { formatUsd, getListing, listings } from '@cf-bench/dataset';
import type { PageProps } from 'waku/router';

export default async function StayDetailPage({ id }: PageProps<'/stays/[id]'>) {
  const listing = getListing(id);

  if (!listing) {
    return (
      <>
        <title>Stay not found</title>
        <h1 className="h1">Stay not found</h1>
        <a className="pill section" href="/stays">
          Back to stays
        </a>
      </>
    );
  }

  return (
    <>
      <title>{listing.title}</title>
      <a className="pill" href="/stays">
        Back to stays
      </a>
      <section className="hero section">
        <p className="eyebrow">Listing detail</p>
        <h1 className="h1">{listing.title}</h1>
        <p className="muted">
          {listing.neighborhood}, {listing.city}, {listing.country}
        </p>
      </section>
      <section className="card">
        <p>
          {formatUsd(listing.pricePerNight)} <span className="muted small">/ night</span>
        </p>
        <p className="muted small">
          {listing.rating} ★ • {listing.reviews} reviews • {listing.maxGuests} guests
        </p>
        <div className="tags section">
          {listing.tags.map((tag) => (
            <span key={tag} className="tag">
              {tag}
            </span>
          ))}
        </div>
        <div className="section" data-testid="stay-description" dangerouslySetInnerHTML={{ __html: listing.descriptionHtml }} />
      </section>
    </>
  );
}

export const getConfig = async () =>
  ({
    render: 'static',
    staticPaths: listings.map((listing) => listing.id),
  }) as const;

// apps/qwik/src/routes/stays/[id]/index.tsx
import { component$ } from "@qwik.dev/core";
import { Link, routeLoader$ } from "@qwik.dev/router";
import { formatUsd, getListing } from "@cf-bench/dataset";
export const useStay = routeLoader$(({ params }) => {
  return { listing: getListing(params.id) };
});

export default component$(() => {
  const { listing } = useStay().value;

  if (!listing) {
    return (
      <>
        <h1 class="h1">Stay not found</h1>
        <div class="card" style="padding:16px">
          <p>Unknown listing.</p>
          <Link class="pill" href="/stays">Back</Link>
        </div>
      </>
    );
  }

  return (
    <>
      <h1 class="h1">{listing.title}</h1>
      <div class="card" style="padding:16px">
        <div class="muted small">
          {listing.city}, {listing.country} • {listing.bedrooms} bd • {listing.baths} ba • up to {listing.maxGuests} guests
        </div>

        <div style="margin-top:10px;display:flex;justify-content:space-between;gap:14px;flex-wrap:wrap">
          <div class="pill">★ {listing.rating} <span class="muted">({listing.reviews})</span></div>
          <div class="pill"><strong>{formatUsd(listing.pricePerNight)}</strong> <span class="muted">/ night</span></div>
          <Link class="pill" href="/stays">← Back to results</Link>
        </div>

        <div data-testid="stay-description" style="margin-top:14px" dangerouslySetInnerHTML={listing.descriptionHtml as any} />
      </div>
    </>
  );
});
