// apps/qwik/src/root.tsx
import { component$, useVisibleTask$ } from "@qwik.dev/core";
import { Link, QwikCityProvider, RouterOutlet } from "@qwik.dev/router";
import { RouterHead } from "./components/router-head/router-head";
import "@cf-bench/ui/styles.css";

export default component$(() => {
  useVisibleTask$(() => {
    const w = window as any;
    const root = (w.__CF_BENCH__ = w.__CF_BENCH__ || {});
    const hydration = (root.hydration = root.hydration || {});
    hydration.endMs = performance.now();
  });

  return (
    <QwikCityProvider>
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <script
          dangerouslySetInnerHTML={`(function(){var w=window;w.__CF_BENCH__=w.__CF_BENCH__||{};var h=w.__CF_BENCH__.hydration=w.__CF_BENCH__.hydration||{};if(h.startMs==null)h.startMs=performance.now();})();`}
        />
        <RouterHead />
      </head>
      <body lang="en">
        <header class="container nav">
          <Link class="brand" href="/">CF Bench</Link>
          <nav class="links">
            <Link class="pill" href="/stays">Stays</Link>
            <Link class="pill" href="/chart">Chart</Link>
            <Link class="pill" href="/media">Media</Link>
            <Link class="pill" href="/blog">Blog</Link>
          </nav>
        </header>

        <main class="container">
          <RouterOutlet />
          <div class="footer">Benchmark route surface on Cloudflare Workers.</div>
        </main>

      </body>
    </QwikCityProvider>
  );
});

// apps/tanstack-start/app/routes/__root.tsx
import { HeadContent, Link, Outlet, Scripts, createRootRoute } from "@tanstack/react-router";
import { HydrationMarker } from "../components/hydration-marker";
import "@cf-bench/ui/styles.css";

export const Route = createRootRoute({
  head: () => ({
    meta: [
      { charSet: "utf-8" },
      { name: "viewport", content: "width=device-width, initial-scale=1" },
      { title: "CF Bench" },
    ],
  }),
  component: RootComponent,
});

function RootComponent() {
  return (
    <html lang="en">
      <head>
        <HeadContent />
      </head>
      <body>
        <div>
          <header className="container nav">
            <Link className="brand" to="/">CF Bench</Link>
            <nav className="links">
              <Link className="pill" to="/stays">Stays</Link>
              <Link className="pill" to="/chart">Chart</Link>
              <Link className="pill" to="/media">Media</Link>
              <Link className="pill" to="/blog">Blog</Link>
            </nav>
          </header>

          <main className="container">
            <Outlet />
            <div className="footer">Benchmark route surface on Cloudflare Workers.</div>
          </main>
        </div>
        <Scripts />
        <HydrationMarker />
      </body>
    </html>
  );
}
