// apps/sveltekit/src/routes/+page.svelte
<h1 class="h1">Framework benchmark harness</h1>

<div class="grid cols-3">
  <div class="card" style="padding:16px">
    <h2>SPA-like</h2>
    <p class="muted">Interactive chart with symbol switching.</p>
    <a class="btn" href="/chart">Open chart</a>
  </div>
  <div class="card" style="padding:16px">
    <h2>App pages</h2>
    <p class="muted">Listings index + detail pages.</p>
    <a class="btn" href="/stays">Browse stays</a>
  </div>
  <div class="card" style="padding:16px">
    <h2>SSG blog</h2>
    <p class="muted">Prerendered at build time.</p>
    <a class="btn" href="/blog">Read blog</a>
  </div>
</div>

// apps/tanstack-start/app/routes/index.tsx
import { Link, createFileRoute } from "@tanstack/react-router";

export const Route = createFileRoute("/")({
  component: Home,
});

function Home() {
  return (
    <>
      <h1 className="h1">Framework benchmark harness</h1>
      <div className="grid cols-3">
        <div className="card" style={{ padding: 16 }}>
          <h2>SPA-like</h2>
          <p className="muted">Interactive chart with symbol switching.</p>
          <Link className="btn" to="/chart">Open chart</Link>
        </div>
        <div className="card" style={{ padding: 16 }}>
          <h2>App pages</h2>
          <p className="muted">Listings index + detail pages.</p>
          <Link className="btn" to="/stays">Browse stays</Link>
        </div>
        <div className="card" style={{ padding: 16 }}>
          <h2>SSG blog</h2>
          <p className="muted">Static-friendly routes.</p>
          <Link className="btn" to="/blog">Read blog</Link>
        </div>
      </div>
    </>
  );
}
