// apps/nuxt/app/pages/stays/[id].vue
<script setup lang="ts">
import { getListing, formatUsd } from "@cf-bench/dataset";

useBenchPage("detail");

const route = useRoute();
const listing = getListing(String(route.params.id || ""));

if (!listing) {
  throw createError({ statusCode: 404, statusMessage: "Listing not found" });
}
</script>

<template>
  <div>
    <NuxtLink class="pill" to="/stays">← Back to stays</NuxtLink>
    <h1 class="h1">{{ listing.title }}</h1>
    <div class="small muted">{{ listing.city }}, {{ listing.country }} • {{ listing.neighborhood }}</div>
    <div class="card" style="margin-top: 12px">
      <div style="margin-bottom: 12px">
        <strong>{{ formatUsd(listing.pricePerNight) }}</strong> <span class="muted small">/ night</span>
      </div>
      <div data-testid="stay-description" v-html="listing.descriptionHtml" />
    </div>
  </div>
</template>

// apps/svelte/src/routes/stays/[id]/+page.svelte
<script lang="ts">
  import { formatUsd, type Listing } from "@cf-bench/dataset";
  export let data: { listing: Listing | undefined };
</script>

{#if data.listing}
  <h1 class="h1">{data.listing.title}</h1>

  <div class="card" style="padding:16px">
    <div class="muted small">
      {data.listing.city}, {data.listing.country} • {data.listing.bedrooms} bd • {data.listing.baths} ba • up to {data.listing.maxGuests} guests
    </div>

    <div style="margin-top:10px;display:flex;justify-content:space-between;gap:14px;flex-wrap:wrap">
      <div class="pill">★ {data.listing.rating} <span class="muted">({data.listing.reviews})</span></div>
      <div class="pill"><strong>{formatUsd(data.listing.pricePerNight)}</strong> <span class="muted">/ night</span></div>
      <a class="pill" href="/stays">← Back to results</a>
    </div>

    <div data-testid="stay-description" style="margin-top:14px">
      {@html data.listing.descriptionHtml}
    </div>
  </div>
{:else}
  <h1 class="h1">Stay not found</h1>
  <div class="card" style="padding:16px">
    <p>Unknown listing.</p>
    <a class="pill" href="/stays">Back</a>
  </div>
{/if}
