// apps/next/app/blog/[slug]/page.tsx
import { getPost } from "@cf-bench/dataset";

export const dynamic = "force-dynamic";

export default async function Page({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const p = getPost(slug);
  if (!p) {
    return (
      <>
        <h1 className="h1">Post not found</h1>
        <a className="pill" href="/blog">Back</a>
      </>
    );
  }
  return (
    <>
      <h1 className="h1">{p.title}</h1>
      <div className="muted small">{p.dateISO} • {p.readingMinutes} min read</div>
      <div className="card" style={{ padding: 16, marginTop: 14 }}>
        <div data-testid="blog-html" dangerouslySetInnerHTML={{ __html: p.html }} />
      </div>
      <div style={{ marginTop: 14 }}>
        <a className="pill" href="/blog">← Back to blog</a>
      </div>
    </>
  );
}

// apps/svelte/src/routes/blog/[slug]/+page.svelte
<script lang="ts">
  import type { BlogPost } from "@cf-bench/dataset";
  export let data: { post: BlogPost | undefined };
</script>

{#if data.post}
  <h1 class="h1">{data.post.title}</h1>
  <div class="muted small">{data.post.dateISO} • {data.post.readingMinutes} min read</div>
  <div class="card" data-testid="blog-html" style="padding:16px;margin-top:14px">
    {@html data.post.html}
  </div>
  <div style="margin-top:14px">
    <a class="pill" href="/blog">← Back to blog</a>
  </div>
{:else}
  <h1 class="h1">Post not found</h1>
  <a class="pill" href="/blog">Back</a>
{/if}
