// apps/honox/app/routes/hifi/stays/[id].tsx
import { createRoute } from "honox/factory";
import { getListing } from "@cf-bench/dataset";
import { getHifiStayDetailParts } from "@cf-bench/hifi-shell";

export default createRoute((c) => {
	const id = c.req.param("id") ?? "";
	const listing = getListing(id);
	const parts = getHifiStayDetailParts(listing);
	if (!listing) {
		c.status(404);
	}
	return c.render(
		<>
			<script async src="/__bench/sdk/maps.js" />
			<script async src="/__bench/sdk/analytics.js" />
			<div dangerouslySetInnerHTML={{ __html: parts.body }} />
			{listing ? <script dangerouslySetInnerHTML={{ __html: parts.script }} /> : null}
		</>,
		{ title: listing ? listing.title : "Stay not found", hifi: true }
	);
});

// apps/nuxt/app/pages/hifi/stays/[id].vue
<script setup lang="ts">
import { getListing } from "@cf-bench/dataset";
import { attachHifiBookingForms, getHifiStayDetailParts } from "@cf-bench/hifi-shell";
import { htmlCacheHeader } from "@cf-bench/bench-cache";

const requestHeaders = useRequestHeaders(["x-cf-bench-profile"]);
const profile = requestHeaders["x-cf-bench-profile"] || null;
const cacheControl = useResponseHeader("cache-control");
cacheControl.value = htmlCacheHeader("/hifi/stays/:id", profile);

const route = useRoute();
const listing = getListing(String(route.params.id || ""));
const parts = getHifiStayDetailParts(listing);

useHead({
  title: listing?.title ?? "Stay not found",
  script: [
    { src: "/__bench/sdk/maps.js", async: true },
    { src: "/__bench/sdk/analytics.js", async: true },
  ],
});

onMounted(() => {
  attachHifiBookingForms();
});
</script>

<template>
  <div v-html="parts.body" />
</template>
