// apps/qwik/src/routes/blog/[slug]/index.tsx
import { component$ } from "@qwik.dev/core";
import { routeLoader$ } from "@qwik.dev/router";
import type { StaticGenerateHandler } from "@qwik.dev/router";
import { blogPosts, getPost } from "@cf-bench/dataset";

export const onStaticGenerate: StaticGenerateHandler = async () => {
  return {
    params: blogPosts.map((p) => ({ slug: p.slug })),
  };
};

export const usePost = routeLoader$(({ params }) => {
  return { post: getPost(params.slug) };
});

export default component$(() => {
  const { post } = usePost().value;
  if (!post) {
    return (
      <>
        <h1 class="h1">Post not found</h1>
        <a class="pill" href="/blog">Back</a>
      </>
    );
  }

  return (
    <>
      <h1 class="h1">{post.title}</h1>
      <div class="muted small">{post.dateISO} • {post.readingMinutes} min read</div>
      <div class="card" style="padding:16px;margin-top:14px">
        <div data-testid="blog-html" dangerouslySetInnerHTML={post.html as any} />
      </div>
      <div style="margin-top:14px">
        <a class="pill" href="/blog">← Back to blog</a>
      </div>
    </>
  );
});

// apps/waku/src/pages/blog/[slug].tsx
import { blogPosts, getPost } from '@cf-bench/dataset';
import type { PageProps } from 'waku/router';

export default async function BlogPostPage({ slug }: PageProps<'/blog/[slug]'>) {
  const post = getPost(slug);

  if (!post) {
    return (
      <>
        <title>Post not found</title>
        <h1 className="h1">Post not found</h1>
        <a className="pill section" href="/blog">
          Back to blog
        </a>
      </>
    );
  }

  return (
    <>
      <title>{post.title}</title>
      <a className="pill" href="/blog">
        Back to blog
      </a>
      <section className="hero section">
        <p className="eyebrow">Blog post</p>
        <h1 className="h1">{post.title}</h1>
        <p className="muted small">
          {post.dateISO} • {post.readingMinutes} min read
        </p>
      </section>
      <article className="card">
        <div data-testid="blog-html" dangerouslySetInnerHTML={{ __html: post.html }} />
      </article>
    </>
  );
}

export const getConfig = async () =>
  ({
    render: 'static',
    staticPaths: blogPosts.map((post) => post.slug),
  }) as const;
