// apps/svelte/src/routes/blog/[slug]/+page.svelte
<script lang="ts">
  import type { BlogPost } from "@cf-bench/dataset";
  export let data: { post: BlogPost | undefined };
</script>

{#if data.post}
  <h1 class="h1">{data.post.title}</h1>
  <div class="muted small">{data.post.dateISO} • {data.post.readingMinutes} min read</div>
  <div class="card" data-testid="blog-html" style="padding:16px;margin-top:14px">
    {@html data.post.html}
  </div>
  <div style="margin-top:14px">
    <a class="pill" href="/blog">← Back to blog</a>
  </div>
{:else}
  <h1 class="h1">Post not found</h1>
  <a class="pill" href="/blog">Back</a>
{/if}

// apps/nuxt/app/pages/blog/[slug].vue
<script setup lang="ts">
import { getPost } from "@cf-bench/dataset";

useBenchPage("detail");

const route = useRoute();
const post = getPost(String(route.params.slug || ""));

if (!post) {
  throw createError({ statusCode: 404, statusMessage: "Post not found" });
}
</script>

<template>
  <div>
    <NuxtLink class="pill" to="/blog">← Back to blog</NuxtLink>
    <h1 class="h1">{{ post.title }}</h1>
    <div class="small muted">{{ post.dateISO }} • {{ post.readingMinutes }} min read</div>
    <div class="card" style="margin-top: 12px">
      <div data-testid="blog-html" v-html="post.html" />
    </div>
  </div>
</template>
