// apps/react/src/pages/Blog.tsx
import { Link } from "react-router-dom";
import { blogPosts } from "@cf-bench/dataset";

export function Blog() {
    return (
        <>
            <h1 className="h1">Blog</h1>

            <div className="grid cols-2">
                {blogPosts.map((post) => (
                    <Link
                        key={post.slug}
                        to={`/blog/${post.slug}`}
                        className="card blog-card"
                        data-testid="blog-post-card"
                    >
                        <h2>{post.title}</h2>
                        <p className="muted small">
                            {post.dateISO} • {post.readingMinutes} min read
                        </p>
                        <p className="muted">{post.excerpt}</p>
                        <div className="tags">
                            {post.tags.map((t) => (
                                <span key={t} className="tag">{t}</span>
                            ))}
                        </div>
                    </Link>
                ))}
            </div>
        </>
    );
}

// apps/nuxt/app/pages/blog/index.vue
<script setup lang="ts">
import { blogPosts } from "@cf-bench/dataset";

useBenchPage("list");
</script>

<template>
  <div>
    <h1 class="h1">Blog</h1>
    <div class="grid cols-2">
      <NuxtLink
        v-for="post in blogPosts"
        :key="post.slug"
        :to="`/blog/${post.slug}`"
        data-testid="blog-post-card"
        class="card"
      >
        <div style="font-weight: 700">{{ post.title }}</div>
        <div class="small muted">{{ post.dateISO }} • {{ post.readingMinutes }} min read</div>
        <p class="muted">{{ post.excerpt }}</p>
      </NuxtLink>
    </div>
  </div>
</template>
