// apps/qwik/src/routes/blog/[slug]/index.tsx
import { component$ } from "@qwik.dev/core";
import { routeLoader$ } from "@qwik.dev/router";
import type { StaticGenerateHandler } from "@qwik.dev/router";
import { blogPosts, getPost } from "@cf-bench/dataset";

export const onStaticGenerate: StaticGenerateHandler = async () => {
  return {
    params: blogPosts.map((p) => ({ slug: p.slug })),
  };
};

export const usePost = routeLoader$(({ params }) => {
  return { post: getPost(params.slug) };
});

export default component$(() => {
  const { post } = usePost().value;
  if (!post) {
    return (
      <>
        <h1 class="h1">Post not found</h1>
        <a class="pill" href="/blog">Back</a>
      </>
    );
  }

  return (
    <>
      <h1 class="h1">{post.title}</h1>
      <div class="muted small">{post.dateISO} • {post.readingMinutes} min read</div>
      <div class="card" style="padding:16px;margin-top:14px">
        <div data-testid="blog-html" dangerouslySetInnerHTML={post.html as any} />
      </div>
      <div style="margin-top:14px">
        <a class="pill" href="/blog">← Back to blog</a>
      </div>
    </>
  );
});

// apps/next/app/blog/[slug]/page.tsx
import { blogPosts, getPost } from "@cf-bench/dataset";

export const dynamic = "error";

export function generateStaticParams() {
  return blogPosts.map((post) => ({ slug: post.slug }));
}

export default async function Page({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const p = getPost(slug);
  if (!p) {
    return (
      <>
        <h1 className="h1">Post not found</h1>
        <a className="pill" href="/blog">Back</a>
      </>
    );
  }
  return (
    <>
      <h1 className="h1">{p.title}</h1>
      <div className="muted small">{p.dateISO} • {p.readingMinutes} min read</div>
      <div className="card" style={{ padding: 16, marginTop: 14 }}>
        <div data-testid="blog-html" dangerouslySetInnerHTML={{ __html: p.html }} />
      </div>
      <div style={{ marginTop: 14 }}>
        <a className="pill" href="/blog">← Back to blog</a>
      </div>
    </>
  );
}
