// apps/hono-solid/src/components/Layout.tsx
import { JSX } from "solid-js";

export function Layout(props: { title: string; children: JSX.Element }) {
  return (
    <div>
      <header class="container nav">
        <a class="brand" href="/">CF Bench</a>
        <nav class="links">
          <a class="pill" href="/stays">Stays</a>
          <a class="pill" href="/chart">Chart</a>
          <a class="pill" href="/media">Media</a>
          <a class="pill" href="/blog">Blog</a>
        </nav>
      </header>

      <main class="container">
        <h1 class="h1">{props.title}</h1>
        {props.children}
        <div class="footer">Benchmark route surface on Cloudflare Workers.</div>
      </main>
    </div>
  );
}

// apps/next/app/layout.tsx
import Link from "next/link";
import type { Viewport } from "next";
import "./globals.css";
import { HydrationMarker } from "./hydration-marker";

export const metadata = {
  title: "CF Bench",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <header className="container nav">
          <Link className="brand" href="/" prefetch={false}>CF Bench</Link>
          <nav className="links">
            <Link className="pill" href="/stays" prefetch={false}>Stays</Link>
            <Link className="pill" href="/chart" prefetch={false}>Chart</Link>
            <Link className="pill" href="/media" prefetch={false}>Media</Link>
            <Link className="pill" href="/blog" prefetch={false}>Blog</Link>
          </nav>
        </header>

        <main className="container">
          {children}
          <div className="footer">Benchmark route surface on Cloudflare Workers.</div>
        </main>
        <HydrationMarker />
      </body>
    </html>
  );
}
