// apps/nuxt/app/pages/hifi/stays/index.vue
<script setup lang="ts">
import { queryListings } from "@cf-bench/dataset";
import { renderHifiStaysListBody } from "@cf-bench/hifi-shell";
import { htmlCacheHeader } from "@cf-bench/bench-cache";

const requestHeaders = useRequestHeaders(["x-cf-bench-profile"]);
const profile = requestHeaders["x-cf-bench-profile"] || null;
const cacheControl = useResponseHeader("cache-control");
cacheControl.value = htmlCacheHeader("/hifi/stays", profile);

useHead({
  title: "Stays (hifi)",
  script: [
    { src: "/__bench/sdk/maps.js", async: true },
    { src: "/__bench/sdk/analytics.js", async: true },
  ],
});

const listings = queryListings({ page: 1, pageSize: 12 }).results;
const bodyHtml = renderHifiStaysListBody(listings);
</script>

<template>
  <div v-html="bodyHtml" />
</template>

// apps/honox/app/routes/hifi/stays/index.tsx
import { createRoute } from "honox/factory";
import { queryListings } from "@cf-bench/dataset";
import { renderHifiStaysListBody } from "@cf-bench/hifi-shell";

export default createRoute((c) => {
	const listings = queryListings({ page: 1, pageSize: 12 }).results;
	const bodyHtml = renderHifiStaysListBody(listings);
	return c.render(
		<>
			<script async src="/__bench/sdk/maps.js" />
			<script async src="/__bench/sdk/analytics.js" />
			<div dangerouslySetInnerHTML={{ __html: bodyHtml }} />
		</>,
		{ title: "Stays (hifi)", hifi: true }
	);
});
