// apps/react-router/app/routes/chart.tsx
import { useEffect, useMemo, useRef, useState, useTransition, useDeferredValue } from "react";
import { chartSymbols, chartTimeframes } from "../lib/data";
import {
  getChartFetchOptions,
  markChartError,
  markChartReady,
  startChartSwitch,
  updateChartCoreMetrics,
} from "@cf-bench/bench-types";

type ChartModule = typeof import("@cf-bench/chart-core");
type ChartInstance = ReturnType<ChartModule["createChart"]>;

async function fetchCandles(symbol: string, timeframe: string, points: number) {
  const opts = getChartFetchOptions();
  const res = await fetch(
    `/api/prices?symbol=${encodeURIComponent(symbol)}&timeframe=${encodeURIComponent(timeframe)}&points=${points}`,
    opts
  );
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  return (await res.json()) as { candles: any[] };
}

const defaultIndicators = { sma20: true, sma50: false, ema20: false, volume: true };

export default function ChartRoute() {
  const [symbol, setSymbol] = useState("BTC");
  const [timeframe, setTimeframe] = useState<(typeof chartTimeframes)[number]>("1h");
  const [indicators, setIndicators] = useState(defaultIndicators);
  const [status, setStatus] = useState<"idle" | "loading" | "ready" | "error">("idle");
  const [chartReady, setChartReady] = useState(false);
  const [isPending, startTransition] = useTransition();
  const deferredIndicators = useDeferredValue(indicators);
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const chartRef = useRef<ChartInstance | null>(null);

  const chartOptions = useMemo(
    () => ({
      initialViewport: 180,
      onStats: (stats: unknown) => updateChartCoreMetrics(stats as never),
    }),
    []
  );

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    if (!chartRef.current) {
      let cancelled = false;
      requestAnimationFrame(() => {
        void (async () => {
          const { createChart } = await import("@cf-bench/chart-core");
          if (cancelled || chartRef.current) return;
          const chart = createChart(canvas, chartOptions);
          chartRef.current = chart;
          requestAnimationFrame(() => {
            if (cancelled) return;
            chart.setIndicators(deferredIndicators);
            chart.resize();
            setChartReady(true);
          });
        })();
      });
      return () => {
        cancelled = true;
      };
      return;
    }
    requestAnimationFrame(() => {
      chartRef.current?.setIndicators(deferredIndicators);
    });
  }, [chartOptions, deferredIndicators]);

  useEffect(() => {
    let cancelled = false;
    async function run() {
      setStatus("loading");
      const points = timeframe === "1m" ? 900 : timeframe === "5m" ? 700 : timeframe === "15m" ? 520 : 360;
      startChartSwitch();
      try {
        const data = await fetchCandles(symbol, timeframe, points);
        if (cancelled) return;
        requestAnimationFrame(() => {
          chartRef.current?.setCandles(data.candles);
        });
        markChartReady(symbol, timeframe);
        setStatus("ready");
      } catch (error) {
        markChartError(error instanceof Error ? error : String(error));
        setStatus("error");
      }
    }
    void run();
    return () => {
      cancelled = true;
    };
  }, [symbol, timeframe]);

  return (
    <>
      <h1 className="h1">Chart (SPA-like)</h1>
      <div className="card" style={{ padding: 14 }}>
        <div style={{ display: "flex", alignItems: "center", gap: 12, flexWrap: "wrap" }}>
          <div className="pill">
            <span className="muted small">Symbol</span>
            <select
              data-testid="symbol-select"
              className="input"
              style={{ width: 140 }}
              value={symbol}
              onChange={(event) =>
                startTransition(() => {
                  setSymbol(event.target.value);
                })
              }
            >
              {chartSymbols.map((item) => (
                <option key={item} value={item}>
                  {item}
                </option>
              ))}
            </select>
          </div>
          <div className="pill">
            <span className="muted small">Timeframe</span>
            <select
              data-testid="timeframe-select"
              className="input"
              style={{ width: 120 }}
              value={timeframe}
              onChange={(event) =>
                startTransition(() => {
                  setTimeframe(event.target.value as (typeof chartTimeframes)[number]);
                })
              }
            >
              {chartTimeframes.map((item) => (
                <option key={item} value={item}>
                  {item}
                </option>
              ))}
            </select>
          </div>
          <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
            {(["sma20", "sma50", "ema20", "volume"] as const).map((key) => (
              <label key={key} className="muted small" style={{ display: "flex", gap: 6, alignItems: "center" }}>
                <input
                  type="checkbox"
                  checked={indicators[key]}
                  onChange={(event) =>
                    startTransition(() => {
                      setIndicators((prev) => ({ ...prev, [key]: event.target.checked }));
                    })
                  }
                />
                {key.toUpperCase()}
              </label>
            ))}
          </div>
          <div className="muted small">{isPending || status === "loading" ? "Loading candles…" : status === "error" ? "Error" : "Ready"}</div>
        </div>
        <div className="muted small" style={{ marginTop: 10 }}>
          Pan: drag • Zoom: mousewheel/trackpad • Crosshair: move cursor
        </div>
        <div style={{ height: 420, marginTop: 12, position: "relative" }}>
          {!chartReady && (
            <div
              style={{
                position: "absolute",
                inset: 0,
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                background: "var(--bg)",
                borderRadius: 12,
                border: "1px solid var(--border)",
              }}
            >
              <span className="muted">Loading chart…</span>
            </div>
          )}
          <canvas
            ref={canvasRef}
            data-testid="chart-canvas"
            style={{
              width: "100%",
              height: "100%",
              borderRadius: 12,
              border: "1px solid var(--border)",
              opacity: chartReady ? 1 : 0,
              transition: "opacity 0.2s ease-in-out",
            }}
          />
        </div>
      </div>
    </>
  );
}

// apps/nuxt/app/pages/chart.vue
<script setup lang="ts">
import { chartSymbols, chartTimeframes } from "@cf-bench/dataset";
import {
  getChartFetchOptions,
  markChartError,
  markChartReady,
  startChartSwitch,
  updateChartCoreMetrics,
} from "@cf-bench/bench-types";

useBenchPage("chart");

type ChartModule = typeof import("@cf-bench/chart-core");
type ChartInstance = ReturnType<ChartModule["createChart"]>;

const symbol = ref("BTC");
const timeframe = ref<(typeof chartTimeframes)[number]>("1h");
const indicators = reactive({
  sma20: true,
  sma50: false,
  ema20: false,
  volume: true,
});
const status = ref<"idle" | "loading" | "ready" | "error">("idle");
const chartReady = ref(false);
const canvasRef = ref<HTMLCanvasElement | null>(null);
let chart: ChartInstance | null = null;

async function fetchCandles() {
  const points = timeframe.value === "1m" ? 900 : timeframe.value === "5m" ? 700 : timeframe.value === "15m" ? 520 : 360;
  const opts = getChartFetchOptions();
  const res = await fetch(
    `/api/prices?symbol=${encodeURIComponent(symbol.value)}&timeframe=${encodeURIComponent(timeframe.value)}&points=${points}`,
    opts
  );
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  return (await res.json()) as { candles: any[] };
}

function currentIndicators() {
  return {
    sma20: indicators.sma20,
    sma50: indicators.sma50,
    ema20: indicators.ema20,
    volume: indicators.volume,
  };
}

async function refreshChart() {
  startChartSwitch();
  status.value = "loading";
  try {
    const data = await fetchCandles();
    chart?.setIndicators(currentIndicators());
    chart?.setCandles(data.candles);
    markChartReady(symbol.value, timeframe.value);
    status.value = "ready";
  } catch (error) {
    markChartError(error instanceof Error ? error : String(error));
    status.value = "error";
  }
}

onMounted(async () => {
  if (!canvasRef.value) return;
  const { createChart } = await import("@cf-bench/chart-core");
  chart = createChart(canvasRef.value, {
    initialViewport: 180,
    onStats: (stats) => updateChartCoreMetrics(stats as never),
  });
  chart.resize();
  chartReady.value = true;
  await refreshChart();
});

watch([symbol, timeframe], async () => {
  if (!chart) return;
  await refreshChart();
});

watch(
  () => currentIndicators(),
  () => {
    chart?.setIndicators(currentIndicators());
  },
  { deep: true }
);
</script>

<template>
  <div>
    <h1 class="h1">Chart (SPA-like)</h1>
    <div class="card" style="padding: 14px">
      <div style="display: flex; align-items: center; gap: 12px; flex-wrap: wrap">
        <div class="pill">
          <span class="muted small">Symbol</span>
          <select v-model="symbol" data-testid="symbol-select" class="input" style="width: 140px">
            <option v-for="item in chartSymbols" :key="item" :value="item">{{ item }}</option>
          </select>
        </div>

        <div class="pill">
          <span class="muted small">Timeframe</span>
          <select v-model="timeframe" data-testid="timeframe-select" class="input" style="width: 120px">
            <option v-for="item in chartTimeframes" :key="item" :value="item">{{ item }}</option>
          </select>
        </div>

        <div style="display: flex; align-items: center; gap: 10px">
          <label class="muted small" style="display: flex; gap: 6px; align-items: center">
            <input v-model="indicators.sma20" type="checkbox" />
            SMA20
          </label>
          <label class="muted small" style="display: flex; gap: 6px; align-items: center">
            <input v-model="indicators.sma50" type="checkbox" />
            SMA50
          </label>
          <label class="muted small" style="display: flex; gap: 6px; align-items: center">
            <input v-model="indicators.ema20" type="checkbox" />
            EMA20
          </label>
          <label class="muted small" style="display: flex; gap: 6px; align-items: center">
            <input v-model="indicators.volume" type="checkbox" />
            Volume
          </label>
        </div>

        <div class="muted small">{{ status === "loading" ? "Loading candles…" : status === "error" ? "Error" : "Ready" }}</div>
      </div>

      <div class="muted small" style="margin-top: 10px">
        Pan: drag • Zoom: mousewheel/trackpad • Crosshair: move cursor
      </div>

      <div style="height: 420px; margin-top: 12px; position: relative">
        <div
          v-if="!chartReady"
          style="position: absolute; inset: 0; display: flex; align-items: center; justify-content: center; background: var(--bg); border-radius: 12px; border: 1px solid var(--border);"
        >
          <span class="muted">Loading chart…</span>
        </div>
        <canvas
          ref="canvasRef"
          data-testid="chart-canvas"
          style="width: 100%; height: 100%; border-radius: 12px; border: 1px solid var(--border)"
        />
      </div>
    </div>
  </div>
</template>
