// apps/qwik/src/routes/hifi/stays/[id]/index.tsx
import { component$, useVisibleTask$ } from "@qwik.dev/core";
import { routeLoader$ } from "@qwik.dev/router";
import { getListing } from "@cf-bench/dataset";
import { attachHifiBookingForms, renderHifiStayDetailBody } from "@cf-bench/hifi-shell";

export const useHifiStay = routeLoader$(({ params, headers }) => {
  headers.set("cache-control", "public, max-age=0, s-maxage=300, stale-while-revalidate=86400");
  return { listing: getListing(params.id) };
});

export default component$(() => {
  const { listing } = useHifiStay().value;

  useVisibleTask$(() => {
    attachHifiBookingForms();
  });

  if (!listing) {
    return (
      <>
        <h1 class="h1">Stay not found</h1>
        <div class="card" style="padding:16px">
          <p>Unknown listing.</p>
          <a class="pill" href="/hifi/stays">Back</a>
        </div>
      </>
    );
  }

  const html = renderHifiStayDetailBody(listing);
  return <div dangerouslySetInnerHTML={html} />;
});

// apps/solidstart/src/routes/hifi/stays/[id].tsx
import { useParams } from "@solidjs/router";
import { Show, onMount } from "solid-js";
import { getListing } from "@cf-bench/dataset";
import { attachHifiBookingForms, renderHifiStayDetailBody } from "@cf-bench/hifi-shell";
import { BenchHeaders } from "../../../lib/headers";

export default function HifiStayDetailPage() {
  const params = useParams<{ id: string }>();
  const listing = () => getListing(params.id);

  onMount(() => {
    attachHifiBookingForms();
  });

  return (
    <>
      <BenchHeaders cacheControl="public, max-age=0, s-maxage=300, stale-while-revalidate=86400" />
      <script async src="/__bench/sdk/maps.js" />
      <script async src="/__bench/sdk/analytics.js" />
      <Show
        when={listing()}
        fallback={
          <>
            <h1 class="h1">Stay not found</h1>
            <div class="card" style="padding:16px">
              <p>Unknown listing.</p>
              <a class="pill" href="/hifi/stays">Back</a>
            </div>
          </>
        }
      >
        {(l) => <div innerHTML={renderHifiStayDetailBody(l())} />}
      </Show>
    </>
  );
}
