// apps/svelte/src/routes/chart/+page.svelte
<script lang="ts">
  import { onMount, onDestroy } from "svelte";
  import { createChart } from "@cf-bench/chart-core";
  import { createChartStore } from "@cf-bench/chart-hooks/svelte";
  import { markChartReady, markChartError, updateChartCoreMetrics } from "@cf-bench/bench-types";

  const chartStore = createChartStore();

  let canvas: HTMLCanvasElement;
  let chart: ReturnType<typeof createChart> | null = null;
  let chartReady = false;
  let rafId: number | null = null;
  let timeoutId: number | null = null;
  let error: string | null = null;

  // Debounce expensive chart updates
  function debouncedUpdate(fn: () => void) {
    if (timeoutId !== null) {
      clearTimeout(timeoutId);
    }
    timeoutId = setTimeout(() => {
      fn();
      timeoutId = null;
    }, 100);
  }

  onMount(async () => {
    try {
      console.log('[SvelteKit Chart] Mounting...');
      if (!canvas) {
        throw new Error('Canvas element not found');
      }

      // Defer chart creation to next frame
      rafId = requestAnimationFrame(() => {
        try {
          chart = createChart(canvas, {
            initialViewport: 180,
            onStats: (stats) => {
              updateChartCoreMetrics(stats);
            }
          });

          // Defer resize to next frame
          requestAnimationFrame(() => {
            try {
              chart?.resize();
              chart?.setIndicators($chartStore.indicators);
              // Set initial data after chart is created
              if ($chartStore.data) {
                chart?.setCandles($chartStore.data.candles);
              }
              chartReady = true;
              markChartReady($chartStore.symbol, $chartStore.timeframe);
              console.log('[SvelteKit Chart] Ready');
            } catch (err) {
              console.error('[SvelteKit Chart] Error during chart setup:', err);
              error = err instanceof Error ? err.message : 'Chart setup failed';
              markChartError(err instanceof Error ? err : 'Chart setup failed');
            }
          });
        } catch (err) {
          console.error('[SvelteKit Chart] Error creating chart:', err);
          error = err instanceof Error ? err.message : 'Chart creation failed';
          markChartError(err instanceof Error ? err : 'Chart creation failed');
        }
      });
    } catch (err) {
      console.error('[SvelteKit Chart] Mount error:', err);
      error = err instanceof Error ? err.message : 'Chart failed to load';
      markChartError(err instanceof Error ? err : 'Chart failed to load');
    }
  });

  onDestroy(() => {
    if (rafId !== null) {
      cancelAnimationFrame(rafId);
    }
    if (timeoutId !== null) {
      clearTimeout(timeoutId);
    }
    chartStore.destroy();
    chart?.destroy?.();
  });

  // Update candles when data changes (with rAF)
  $: if ($chartStore.data && chart && chartReady) {
    debouncedUpdate(() => {
      requestAnimationFrame(() => {
        chart?.setIndicators($chartStore.indicators);
        chart?.setCandles($chartStore.data.candles);
      });
    });
  }

  // Update indicators when changed (with rAF)
  $: if (chart && chartReady) {
    debouncedUpdate(() => {
      requestAnimationFrame(() => {
        chart?.setIndicators($chartStore.indicators);
      });
    });
  }

  function handleSymbolChange(e: Event) {
    const target = e.target as HTMLSelectElement;
    chartStore.setSymbol(target.value);
  }

  function handleTimeframeChange(e: Event) {
    const target = e.target as HTMLSelectElement;
    chartStore.setTimeframe(target.value as any);
  }

  function handleIndicatorChange(key: keyof typeof $chartStore.indicators, e: Event) {
    const target = e.target as HTMLInputElement;
    chartStore.setIndicators((prev) => ({ ...prev, [key]: target.checked }));
  }
</script>

<h1 class="h1">Chart (SPA-like)</h1>

{#if error}
  <div class="card" style="padding: 14px; border: 1px solid red; background: #fee;">
    <h2 style="color: red; margin: 0 0 8px 0;">Chart Error</h2>
    <p style="margin: 0;">{error}</p>
  </div>
{/if}

<div class="card" style="padding: 14px">
  <div style="display: flex; align-items: center; gap: 12px; flex-wrap: wrap">
    <div class="pill">
      <span class="muted small">Symbol</span>
      <select
        data-testid="symbol-select"
        class="input"
        style="width: 140px"
        value={$chartStore.symbol}
        on:change={handleSymbolChange}
      >
        {#each $chartStore.symbols as s}
          <option value={s}>{s}</option>
        {/each}
      </select>
    </div>

    <div class="pill">
      <span class="muted small">Timeframe</span>
      <select
        data-testid="timeframe-select"
        class="input"
        style="width: 120px"
        value={$chartStore.timeframe}
        on:change={handleTimeframeChange}
      >
        {#each $chartStore.timeframes as tf}
          <option value={tf}>{tf}</option>
        {/each}
      </select>
    </div>

    <div style="display: flex; align-items: center; gap: 10px">
      <label class="muted small" style="display: flex; gap: 6px; align-items: center">
        <input
          type="checkbox"
          checked={$chartStore.indicators.sma20}
          on:change={(e) => handleIndicatorChange("sma20", e)}
        />
        SMA20
      </label>
      <label class="muted small" style="display: flex; gap: 6px; align-items: center">
        <input
          type="checkbox"
          checked={$chartStore.indicators.sma50}
          on:change={(e) => handleIndicatorChange("sma50", e)}
        />
        SMA50
      </label>
      <label class="muted small" style="display: flex; gap: 6px; align-items: center">
        <input
          type="checkbox"
          checked={$chartStore.indicators.ema20}
          on:change={(e) => handleIndicatorChange("ema20", e)}
        />
        EMA20
      </label>
      <label class="muted small" style="display: flex; gap: 6px; align-items: center">
        <input
          type="checkbox"
          checked={$chartStore.indicators.volume}
          on:change={(e) => handleIndicatorChange("volume", e)}
        />
        Volume
      </label>
    </div>

    <div class="muted small">
      {$chartStore.status === "loading" ? "Loading…" : $chartStore.status === "error" ? "Error" : "Ready"}
    </div>
  </div>

  <div class="muted small" style="margin-top: 10px">
    Pan: drag • Zoom: mousewheel/trackpad • Crosshair: move cursor
  </div>

  <div style="height: 420px; margin-top: 12px; position: relative">
    {#if !chartReady}
      <div data-testid="chart-loading" style="position: absolute; inset: 0; display: flex; align-items: center; justify-content: center; background: var(--bg); border-radius: 12px; border: 1px solid var(--border);">
        <span class="muted">Loading chart…</span>
      </div>
    {:else}
      <div data-testid="chart-ready" style="position: absolute; inset: 0; pointer-events: none;"></div>
    {/if}
    <canvas
      bind:this={canvas}
      data-testid="chart-canvas"
      style="width: 100%; height: 100%; border-radius: 12px; border: 1px solid var(--border); opacity: {chartReady ? 1 : 0}; transition: opacity 0.2s ease-in-out;"
    ></canvas>
  </div>
</div>

// apps/hono-solid/src/pages/Chart.tsx
import { createEffect, onCleanup, onMount, createSignal, For, Show, ErrorBoundary } from "solid-js";
import { createChart } from "@cf-bench/chart-core";
import { useChart as useChartSolid } from "@cf-bench/chart-hooks/solid";
import { markChartReady, markChartError, updateChartCoreMetrics } from "@cf-bench/bench-types";
import { Layout } from "../components/Layout";

export function Chart() {
  const [error, setError] = createSignal<string | null>(null);

  return (
    <Layout title="Chart (SPA-like)">
      <ErrorBoundary
        fallback={(err) => (
          <div class="card" style="padding: 14px; border: 1px solid red; background: #fee;">
            <h2 style="color: red; margin: 0 0 8px 0;">Chart Error</h2>
            <p style="margin: 0;">{err.message || err.toString() || "Unknown error"}</p>
          </div>
        )}
      >
        <ChartInner onError={setError} />
      </ErrorBoundary>
    </Layout>
  );
}

function ChartInner(props: { onError: (error: string) => void }) {
  const {
    symbol,
    setSymbol,
    timeframe,
    setTimeframe,
    indicators,
    setIndicators,
    status,
    data,
    symbols,
    timeframes,
  } = useChartSolid();

  const [chartReady, setChartReady] = createSignal(false);
  let canvasRef: HTMLCanvasElement | undefined;
  let chart: ReturnType<typeof createChart> | null = null;
  let rafId: number | null = null;

  // Optimize chart initialization with requestAnimationFrame
  onMount(async () => {
    try {
      console.log('[Solid Chart] Mounting...');
      if (!canvasRef) {
        throw new Error('Canvas element not found');
      }

      // Use requestAnimationFrame to avoid blocking main thread
      rafId = requestAnimationFrame(() => {
        try {
          chart = createChart(canvasRef, {
            initialViewport: 180,
            onStats: (stats) => {
              updateChartCoreMetrics(stats);
            },
          });

          // Defer resize to next frame
          requestAnimationFrame(() => {
            try {
              chart?.resize();
              setChartReady(true);
              markChartReady(symbol(), timeframe());
              console.log('[Solid Chart] Ready');
            } catch (err) {
              console.error('[Solid Chart] Error during chart setup:', err);
              const errMsg = err instanceof Error ? err.message : 'Chart setup failed';
              props.onError(errMsg);
              markChartError(errMsg);
            }
          });
        } catch (err) {
          console.error('[Solid Chart] Error creating chart:', err);
          const errMsg = err instanceof Error ? err.message : 'Chart creation failed';
          props.onError(errMsg);
          markChartError(errMsg);
        }
      });
    } catch (err) {
      console.error('[Solid Chart] Mount error:', err);
      const errMsg = err instanceof Error ? err.message : 'Chart failed to load';
      props.onError(errMsg);
      markChartError(errMsg);
    }
  });

  onCleanup(() => {
    if (rafId !== null) {
      cancelAnimationFrame(rafId);
    }
    chart?.destroy();
  });

  // Optimize candle updates - batch with indicators
  createEffect(() => {
    const candles = data();
    const inds = indicators();
    
    if (candles && chart) {
      // Use requestAnimationFrame for smoother updates
      requestAnimationFrame(() => {
        chart?.setIndicators(inds);
        chart?.setCandles(candles.candles);
      });
    }
  });

  // Debounce indicator updates
  createEffect(() => {
    const inds = indicators();
    
    if (chart) {
      requestAnimationFrame(() => {
        chart?.setIndicators(inds);
      });
    }
  });

  return (
    <>
      <h1 class="h1">Chart (SPA-like)</h1>
      <div class="card" style="padding: 14px">
        <div style="display: flex; align-items: center; gap: 12px; flex-wrap: wrap">
          <div class="pill">
            <span class="muted small">Symbol</span>
            <select
              data-testid="symbol-select"
              class="input"
              style="width: 140px"
              value={symbol()}
              onChange={(e) => setSymbol((e.target as HTMLSelectElement).value)}
            >
              <For each={symbols}>
                {(s) => (
                  <option value={s}>
                    {s}
                  </option>
                )}
              </For>
            </select>
          </div>

          <div class="pill">
            <span class="muted small">Timeframe</span>
            <select
              data-testid="timeframe-select"
              class="input"
              style="width: 120px"
              value={timeframe()}
              onChange={(e) => setTimeframe((e.target as HTMLSelectElement).value as any)}
            >
              <For each={timeframes}>
                {(tf) => (
                  <option value={tf}>
                    {tf}
                  </option>
                )}
              </For>
            </select>
          </div>

          <div style="display: flex; align-items: center; gap: 10px">
            <label class="muted small" style="display: flex; gap: 6px; align-items: center">
              <input
                type="checkbox"
                checked={indicators().sma20}
                onChange={(e) => setIndicators((prev) => ({ ...prev, sma20: (e.target as HTMLInputElement).checked }))}
              />
              SMA20
            </label>
            <label class="muted small" style="display: flex; gap: 6px; align-items: center">
              <input
                type="checkbox"
                checked={indicators().sma50}
                onChange={(e) => setIndicators((prev) => ({ ...prev, sma50: (e.target as HTMLInputElement).checked }))}
              />
              SMA50
            </label>
            <label class="muted small" style="display: flex; gap: 6px; align-items: center">
              <input
                type="checkbox"
                checked={indicators().ema20}
                onChange={(e) => setIndicators((prev) => ({ ...prev, ema20: (e.target as HTMLInputElement).checked }))}
              />
              EMA20
            </label>
            <label class="muted small" style="display: flex; gap: 6px; align-items: center">
              <input
                type="checkbox"
                checked={indicators().volume}
                onChange={(e) => setIndicators((prev) => ({ ...prev, volume: (e.target as HTMLInputElement).checked }))}
              />
              Volume
            </label>
          </div>

          <div class="muted small">
            {status() === "loading" ? "Loading…" : status() === "error" ? "Error" : "Ready"}
          </div>
        </div>

        <div class="muted small" style="margin-top: 10px">
          Pan: drag • Zoom: mousewheel/trackpad • Crosshair: move cursor
        </div>

        <div style="height: 420px; margin-top: 12px; position: relative">
          <Show when={!chartReady()}>
            <div data-testid="chart-loading" style="position: absolute; inset: 0; display: flex; align-items: center; justify-content: center; background: var(--bg); border-radius: 12px; border: 1px solid var(--border);">
              <span class="muted">Loading chart…</span>
            </div>
          </Show>
          <Show when={chartReady()}>
            <div data-testid="chart-ready" style="position: absolute; inset: 0; pointer-events: none;"></div>
          </Show>
          <Show when={status() === "error"}>
            <div data-testid="chart-error" style="position: absolute; inset: 0; display: flex; align-items: center; justify-content: center; background: var(--bg); border-radius: 12px; border: 1px solid var(--border);">
              <span class="muted">Chart error</span>
            </div>
          </Show>
          <canvas
            ref={canvasRef}
            data-testid="chart-canvas"
            style="width: 100%; height: 100%; border-radius: 12px; border: 1px solid var(--border); opacity: {chartReady() ? 1 : 0}; transition: opacity 0.2s ease-in-out;"
          />
        </div>
      </div>
    </>
  );
}
