// apps/qwik/src/routes/stays/index.tsx
import { component$ } from "@qwik.dev/core";
import { Link, routeLoader$ } from "@qwik.dev/router";
import { listings, formatUsd } from "@cf-bench/dataset";

export const useStays = routeLoader$(({ url }) => {
  const city = url.searchParams.get("city") ?? "";
  const maxRaw = url.searchParams.get("max") ?? "";
  const maxNum = maxRaw ? Number(maxRaw) : null;

  const cities = Array.from(new Set(listings.map((l) => l.city))).sort();
  const filtered = listings.filter((l) => {
    if (city && l.city !== city) return false;
    if (maxNum != null && Number.isFinite(maxNum) && l.pricePerNight > maxNum) return false;
    return true;
  });

  return { city, maxRaw, cities, filtered };
});

export const StayCard = component$<{ listing: typeof listings[0] }>((props) => {
  return (
    <Link
      class="card"
      data-testid="stay-card"
      href={`/stays/${props.listing.id}`}
      style="padding:14px;display:block"
    >
      <div style="display:flex;justify-content:space-between;gap:12px">
        <div>
          <div style="font-weight:700">{props.listing.title}</div>
          <div class="muted small">
            {props.listing.city}, {props.listing.country} • {props.listing.bedrooms} bd • {props.listing.baths} ba • up to {props.listing.maxGuests} guests
          </div>
        </div>
        <div style="text-align:right">
          <div style="font-weight:700">
            {formatUsd(props.listing.pricePerNight)} <span class="muted small">/ night</span>
          </div>
          <div class="muted small">★ {props.listing.rating} ({props.listing.reviews})</div>
        </div>
      </div>
      <div class="muted small" style="margin-top:10px">{props.listing.summary}</div>
    </Link>
  );
});

export default component$(() => {
  const data = useStays().value;
  return (
    <>
      <h1 class="h1">Stays</h1>

      <form method="get" action="/stays" class="card" style="padding:14px;margin-bottom:14px">
        <div class="grid cols-3">
          <div>
            <div class="small muted">City</div>
            <select class="input" name="city" value={data.city}>
              <option value="">Any</option>
              {data.cities.map((c) => (
                <option value={c} selected={c === data.city}>
                  {c}
                </option>
              ))}
            </select>
          </div>
          <div>
            <div class="small muted">Max price</div>
            <input class="input" name="max" value={data.maxRaw} placeholder="e.g. 250" inputMode="numeric" />
          </div>
          <div style="display:flex;align-items:end">
            <button class="btn" type="submit">Apply</button>
          </div>
        </div>
      </form>

      <div class="grid cols-2">
        {data.filtered.map((l) => (
          <StayCard listing={l} />
        ))}
      </div>
    </>
  );
});

// apps/next/app/stays/page.tsx
import Link from "next/link";
import { listings, formatUsd } from "@cf-bench/dataset";

export default async function Page({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const params = await searchParams;
  const city = typeof params.city === "string" ? params.city : "";
  const maxRaw = typeof params.max === "string" ? params.max : "";
  const maxNum = maxRaw ? Number(maxRaw) : null;

  const cities = Array.from(new Set(listings.map((l) => l.city))).sort();

  const filtered = listings.filter((l) => {
    if (city && l.city !== city) return false;
    if (maxNum != null && Number.isFinite(maxNum) && l.pricePerNight > maxNum) return false;
    return true;
  });

  return (
    <>
      <h1 className="h1">Stays</h1>

      <form method="get" action="/stays" className="card" style={{ padding: 14, marginBottom: 14 }}>
        <div className="grid cols-3">
          <div>
            <div className="small muted">City</div>
            <select className="input" name="city" defaultValue={city}>
              <option value="">Any</option>
              {cities.map((c) => (
                <option key={c} value={c}>
                  {c}
                </option>
              ))}
            </select>
          </div>
          <div>
            <div className="small muted">Max price</div>
            <input className="input" name="max" defaultValue={maxRaw} placeholder="e.g. 250" inputMode="numeric" />
          </div>
          <div style={{ display: "flex", alignItems: "end" }}>
            <button className="btn" type="submit">Apply</button>
          </div>
        </div>
      </form>

      <div className="grid cols-2">
        {filtered.map((l) => (
          <Link
            key={l.id}
            data-testid="stay-card"
            className="card"
            href={`/stays/${l.id}`}
            prefetch={false}
            style={{ padding: 14, display: "block" }}
          >
            <div style={{ display: "flex", justifyContent: "space-between", gap: 12 }}>
              <div>
                <div style={{ fontWeight: 700 }}>{l.title}</div>
                <div className="muted small">
                  {l.city}, {l.country} • {l.bedrooms} bd • {l.baths} ba • up to {l.maxGuests} guests
                </div>
              </div>
              <div style={{ textAlign: "right" }}>
                <div style={{ fontWeight: 700 }}>{formatUsd(l.pricePerNight)} <span className="muted small">/ night</span></div>
                <div className="muted small">★ {l.rating} ({l.reviews})</div>
              </div>
            </div>
            <div className="muted small" style={{ marginTop: 10 }}>{l.summary}</div>
          </Link>
        ))}
      </div>
    </>
  );
}
